Add slider module
wearethefuture-org/shop-auction-back pull request #25
Opened 2021-02-08 17:24 UTC by coldmorning4

2021-02-11 21:56 UTC, coldmorning4 commented on src/files/files.slider.entity.ts
> +}
але в вашому ентіті є прив'язка до продукту 
<img width="992" alt="image" src="https://user-images.githubusercontent.com/59203062/107702399-d781df00-6cc2-11eb-8d00-184674dab573.png">

2021-02-16 12:40 UTC, ArtemBozhok requested changes

2021-02-16 12:40 UTC, ArtemBozhok commented on src/slider/dto/create-slider.dto.ts
> +
зайвий рядок

2021-02-16 12:40 UTC, ArtemBozhok commented on src/slider/dto/create-slider.dto.ts
> +}
перевір усі файли, кожний в кінці повинен мати пустий рядок

2021-02-16 12:40 UTC, ArtemBozhok commented on src/slider/slider.controller.ts
> +
тут не потрібен пустий рядок

2021-02-16 12:40 UTC, ArtemBozhok commented on src/slider/sliders.service.ts
> +      await fs.promises.stat(`${process.env.SLIDER_IMAGES_LOCATION}/${imgName}`);
не правильна енв змінна, подивись в envexample шлях до папки фоток. Усі фотки будемо кидати у одну папку.

2021-02-16 12:40 UTC, ArtemBozhok commented on src/slider/sliders.service.ts
> +      name: file.filename,
ну а тут, якщо хочеш виділити ці файли, то можешь доадати перед генерованим ім'ям slider-

2021-02-23 12:10 UTC, ArtemBozhok requested changes

2021-02-23 12:10 UTC, ArtemBozhok commented on src/slider/dto/create-slider.dto.ts
> +  @IsNotEmpty()
усі інші поля також необхідно опитасти для свагера

2021-02-28 20:27 UTC, coldmorning4 commented on src/files/files.entity.ts
> +  @ManyToOne(() => Slider, slider => slider.files, { onDelete: 'CASCADE' })
<img width="1042" alt="Знімок екрана 2021-02-25 о 16 36 24" src="https://user-images.githubusercontent.com/59203062/109432508-2c885980-7a14-11eb-9a7e-b8fe1082c79b.png">

2021-03-02 12:05 UTC, ArtemBozhok approved these changes

2021-03-02 12:06 UTC, merged