fix function size upload images
wearethefuture-org/shop-auction-back pull request #47
Opened 2021-03-30 14:45 UTC by coldmorning4

2021-03-31 13:06 UTC, ArtemBozhok requested changes
Виправляй конфлікт

2021-04-02 13:40 UTC, ArtemBozhok requested changes

2021-04-02 13:40 UTC, ArtemBozhok commented on src/utils/upload-images.ts
> +import sizeOf from 'image-size'
в залежностях не бачу цієї ліби, тому коли я перейшов на твою гілку проект не білдиться.

2021-04-09 09:44 UTC, vipe4ka-visko4ka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Фікс розмірів фоток](https://trello.com/c/7DgZ2xSY/64-%D1%84%D1%96%D0%BA%D1%81-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80%D1%96%D0%B2-%D1%84%D0%BE%D1%82%D0%BE%D0%BA)

2021-04-09 11:44 UTC, vipe4ka-visko4ka requested changes

2021-04-21 07:33 UTC, vipe4ka-visko4ka approved these changes

2021-04-21 10:04 UTC, ArtemBozhok approved these changes

2021-04-21 10:04 UTC, merged