Admin users logic
wearethefuture-org/shop-auction-back pull request #49
Opened 2021-03-30 16:47 UTC by vasbka

2021-03-31 13:56 UTC, ArtemBozhok requested changes

2021-03-31 13:56 UTC, ArtemBozhok commented on database/migration/seed/data/user.ts
> +    updatedAt: `${new Date()}`,
думаю, що ці поля створюютсья автоматично коли ти сетаєш у базу дані, перевіряв це?

2021-03-31 13:56 UTC, ArtemBozhok commented on src/auth/auth.controller.ts
> +      });
здається в тебе не налаштованний преттір. Бо повинно бути так .find({

2021-03-31 13:56 UTC, ArtemBozhok commented on src/auth/auth.service.ts
>    public async validateUser(email: string, password: string): Promise<any> {
виходить ці параметри не юзаються

2021-03-31 13:56 UTC, ArtemBozhok commented on src/user/dto/create-admin-user.dto.ts
> +
для чого цей пустий файл?

2021-03-31 13:56 UTC, ArtemBozhok commented on src/user/role/dto/create-role.dto.ts
> +    public name: string;
оці паблік можна не юзати

2021-03-31 13:56 UTC, ArtemBozhok commented on src/user/role/role.controller.ts
> +  @Put(':id')
post

2021-03-31 13:56 UTC, ArtemBozhok commented on src/user/role/role.repository.ts
> +import { EntityRepository, Repository } from 'typeorm';
уся ця логіка повинна бути в сервісі, не в репозиторії

2021-03-31 13:56 UTC, ArtemBozhok commented on src/user/user.controller.ts
>      return this.usersRepository.findUser(req.user, id);
і отут звератитсь треба до сервісу

2021-03-31 13:58 UTC, ArtemBozhok commented
і конфлікти виправи

2021-03-31 14:04 UTC, wearethefuture-org commented on yarn.lock
>      detect-libc "^1.0.3"
add this file to git ignore

2021-04-02 11:49 UTC, vasbka reviewed
Comments

2021-04-02 11:50 UTC, ArtemBozhok commented on src/user/dto/create-admin-user.dto.ts
> +
напиши кийсь туду коммент одразу сюди, щоб розуміти.

2021-04-02 11:51 UTC, ArtemBozhok commented on src/user/user.controller.ts
>      return this.usersRepository.findUser(req.user, id);
давай в окремий тікет.

2021-04-02 11:51 UTC, ArtemBozhok approved these changes

2021-04-08 11:39 UTC, merged