TASK 97
wearethefuture-org/shop-auction-back pull request #60
Opened 2021-04-20 11:50 UTC by Kovalova22

2021-04-20 11:57 UTC, Kovalova22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Налаштувати підтягування даних з google](https://trello.com/c/DeiZLF6L/97-%D0%BD%D0%B0%D0%BB%D0%B0%D1%88%D1%82%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D0%BF%D1%96%D0%B4%D1%82%D1%8F%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%B4%D0%B0%D0%BD%D0%B8%D1%85-%D0%B7-google)

2021-04-20 15:11 UTC, vipe4ka-visko4ka requested changes

2021-04-20 15:11 UTC, vipe4ka-visko4ka commented on src/auth/auth.service.ts
> +    const { birthdays, phoneNumbers } = data;
Це винести в окремий сервіс

2021-04-20 15:11 UTC, vipe4ka-visko4ka commented on src/auth/auth.service.ts
> +    }
Перед занесенням юзера в базу, создай обєкт юзера і міняй йому дані в залежності від цих іфів. Дубляж метода userRepository.save в трьох місцях трохи напрягає

2021-04-22 06:35 UTC, vipe4ka-visko4ka requested changes

2021-04-22 06:35 UTC, vipe4ka-visko4ka commented on src/auth/auth.service.ts
> +    }
в тебе уже є іфки нижче на цю логіку, удали цю

2021-04-22 06:56 UTC, vipe4ka-visko4ka approved these changes

2021-04-22 11:51 UTC, merged