Task 74 back functionality of popular products
wearethefuture-org/shop-auction-back pull request #72
Opened 2021-04-30 09:57 UTC by kharkov-timur

2021-04-30 11:46 UTC, ArtemBozhok requested changes

2021-04-30 11:46 UTC, ArtemBozhok commented on src/product/dto/create-product.dto.ts
> +
ти коли створюш продукт то йому передавати рейтинг не потрібно, він має бути дефолтним.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/dto/ratings.dto.ts
> +  public userId: number;
юзера потрібно отримувати, із токена а не передавати хардкодом, таким чином можна стукнути на ендпоінт і накрутит рейтинг.
Запит повинен бути секюрним.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/dto/ratings.dto.ts
> +  public userId: number;
і до речі оці паблік не потрібні.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.controller.ts
> +    return this.ratingsService.addRatings(req.user, body);
от із респонса і бери юзер айді, а не із ДТО

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.entity.ts
> +  public userId: number;
ця колонка не потрібна у тебе є релейшин до юзера.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.entity.ts
> +  public productId: number;
так само як і ця. Якщо ти прописуєш релейшини то ці всі айдішнікі в тебе будуть коли ти зробиш джоін.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.entity.ts
> +  public productId: number;
Ти робиш запит на отримання цього ентіті з джоіном релейшина юзера і продукта і в них можна селектнути айді,  якщо тобі потрібно

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.entity.ts
> +  @ManyToOne(() => Product, (product) => product, { eager: true })
виключай еагер, у продуктах куча ендпоінтів в яких можливо ці релейшини не потрібні, наприклад по характеристикам. 
Грузити релейшин треба тільки там де це необхідно.
Я розумію, що так легше не правити усі ендопінти, але це лишнє навантаження на базу.

2021-04-30 11:46 UTC, ArtemBozhok commented on src/ratings/ratings.service.ts
> +    const {userId, productId} = dto;
писав про юзер айді вище

2021-05-04 12:41 UTC, wearethefuture-org approved these changes

2021-05-04 14:02 UTC, ArtemBozhok approved these changes

2021-05-04 17:30 UTC, merged