Task-74 Fix problem with add first rating
wearethefuture-org/shop-auction-back pull request #77
Opened 2021-05-05 20:00 UTC by kharkov-timur

2021-05-05 20:19 UTC, vipe4ka-visko4ka requested changes

2021-05-05 20:19 UTC, vipe4ka-visko4ka commented on src/ratings/ratings.service.ts
> +    try {
Заміни try catch на 
if (!product)
        throw new NotFoundException(`Продукт з id: ${productId} не знайдено`)

2021-05-05 20:19 UTC, vipe4ka-visko4ka commented on src/ratings/ratings.service.ts
> +      const user = await this.userRepository.findOne(userId);
Юзай Promise all

2021-05-06 09:47 UTC, wearethefuture-org approved these changes

2021-05-06 11:57 UTC, vipe4ka-visko4ka approved these changes

2021-05-06 12:15 UTC, merged