TASK-103 add product to the returned comment
wearethefuture-org/shop-auction-back pull request #82
Opened 2021-05-14 11:49 UTC by maxim-zabolotny

2021-05-14 11:49 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Зробити робочим розділ "Мої відгуки"](https://trello.com/c/GnQTQUQ6/103-%D0%B7%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%87%D0%B8%D0%BC-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB-%D0%BC%D0%BE%D1%97-%D0%B2%D1%96%D0%B4%D0%B3%D1%83%D0%BA%D0%B8)

2021-05-17 11:44 UTC, ArtemBozhok requested changes

2021-05-17 11:44 UTC, ArtemBozhok commented on src/comments/comments.service.ts
> +      .addSelect('category')
може category.key?

2021-05-17 11:44 UTC, ArtemBozhok commented on src/comments/comments.service.ts
>      return !!result.affected;
давай це переробимо і будемо повертати message про успішне видалення. 
Подивись приклад в інших сервсіах.

2021-05-19 20:21 UTC, maxim-zabolotny commented on src/comments/comments.service.ts
>      return !!result.affected;
![image](https://user-images.githubusercontent.com/54500881/118879003-e1863000-b8f8-11eb-9997-6741fd495112.png)

Он же отправляется, или не так нужно?

2021-05-20 13:59 UTC, ArtemBozhok commented on src/comments/comments.service.ts
>      return !!result.affected;
конкретно в цьому методі повертається result.affected а не отой меседж, що на твоєму скріні

2021-05-24 08:58 UTC, ArtemBozhok approved these changes

2021-05-24 08:58 UTC, merged