Task 109 Add the functionality of the "Contact Us" section
wearethefuture-org/shop-auction-back pull request #87
Opened 2021-05-20 14:31 UTC by maxim-zabolotny

2021-05-20 14:37 UTC, maxim-zabolotny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Додати функціонал розділу "Зв'язатися з нами"](https://trello.com/c/KOqs6lZw/109-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D1%96%D0%BE%D0%BD%D0%B0%D0%BB-%D1%80%D0%BE%D0%B7%D0%B4%D1%96%D0%BB%D1%83-%D0%B7%D0%B2%D1%8F%D0%B7%D0%B0%D1%82%D0%B8%D1%81%D1%8F-%D0%B7-%D0%BD%D0%B0%D0%BC%D0%B8)

2021-05-24 11:08 UTC, ArtemBozhok requested changes

2021-05-24 11:08 UTC, ArtemBozhok commented on src/user/user.service.ts
> +    if(res) return {message: 'Ваше повідомлення, успішно відправлено', success: true}
користуйся преттіром

2021-05-26 10:44 UTC, ArtemBozhok approved these changes

2021-05-26 10:44 UTC, merged