Fix search
wearethefuture-org/shop-auction-back pull request #98
Opened 2021-05-27 18:46 UTC by Movchan94

2021-05-28 07:26 UTC, vipe4ka-visko4ka commented on src/product/product.service.ts
>        .orderBy('product.createdAt', 'ASC')
Удостовірься у ПМів чи не повинні шукати логіку по дискріпшену

2021-05-28 09:58 UTC, Movchan94 commented on src/product/product.service.ts
>        .orderBy('product.createdAt', 'ASC')
Ігор дав добро - тільки по нейму пошук.

2021-05-31 16:41 UTC, ArtemBozhok commented on src/product/product.service.ts
>        .orderBy('product.createdAt', 'ASC')
прав конфлікти і попроси Пашу апрувнути

2021-05-31 16:42 UTC, ArtemBozhok requested changes
прав конфлікти і я змерджу

2021-06-01 08:56 UTC, ArtemBozhok approved these changes

2021-06-01 08:56 UTC, merged